
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/artmining?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: "!5dhtmdcks"

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 127.0.0.1
    port: 6379

jwt:
  secret: 12345678901234567890123456789012



---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test

